### PR TITLE
Quick fix for faulty overflow of auction tables

### LINKED ISSUE #383: Fix auction table layout on mobile screens
### Goal
Fix layout of auction table

### Context
The auction table (both for collateral and surplus auctions) looks broken on mobile. 

### Tasks

- [ ] Fix the auction table for mobile screens

### Assets
Current layout:

### PR DESCRIPTION
**Pull request by aomafarag**
Closes #383.

Screenshot from 2022-08-01 11-53-20

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

### CODE REVIEW

**Review by LukSteib — APPROVED** [review]

File: frontend/components/auction/surplus/SurplusAuctionsTable.vue [hunk 1]
```diff
@@ -76,7 +76,7 @@
 <script lang="ts">
 import Vue, { PropType } from 'vue';
 import { Table } from 'ant-design-vue';
-import { SurplusAuctionTransaction } from 'auctions-core/src/types';
+import { SurplusAuction, SurplusAuctionTransaction } from 'auctions-core/src/types';
```
Comment (zoey-kaiser) [inline frontend/components/auction/surplus/SurplusAuctionsTable.vue:79]: We used the wrong type in this file. Please remove the import of the `SurplusAuction` and fix the type (from SurplusAuction to SurplusAuctionTransaction) in this line:

https://github.com/sidestream-tech/unified-auctions-ui/blob/130fbb7e3b808954802cd635b160b9084dd9eced/frontend/components/auction/surplus/SurplusAuctionsTable.vue#L228

**Review by zoey-kaiser — CHANGES_REQUESTED** [review]

**Review by valiafetisov — APPROVED** [review]
