### PR TITLE
Fix token information not showing on dashboard

### LINKED ISSUE #472: Fix token information on dashboard
### Goal
Dashboard page displays token information as expected

### Context
Currently the dashboard page https://unified-auctions.makerdao.com/dashboard doesn't seem to work properly. Token information is stuck in an infinite loading loop. 
Let's investigate and fix

### Assets
image

### Tasks
- [ ] Fix dashboard related problem as described above

### PR DESCRIPTION
**Pull request by aomafarag**
Closes #472.

Screenshot from 2022-09-26 13-20-23

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] issue checkboxes are all addressed
- [x] manually checked my feature / not applicable
- [x] wrote tests / not applicable
- [x] attached screenshots / not applicable

### CODE REVIEW

**Comment by valiafetisov** [comment]
> missing a function for refetching data

The dashboard doesn't need to be refetched, it's just a debugging page.

- Then how refetching solves the problem of initial loading?
- When does the `setup` called initially? Is it called on the dashboard page load or on any page load? – if on any, then it should be fixed and called only on the dashboard page load

>  Also, are the errors in the screenshot (Error: missing revert data in...) normal?

Depends on the network. On the mainnet all collaterals should have uniswap price

**Comment by valiafetisov** [comment]
> same goes for virtually all stores

Yes, because we expect that values on the other stores might change. The dashboard _mostly_ presents things that doesn't change that often – list of collaterals and their addresses, prices (that we only need to know are tradable or not).

> When the dashboard container is mounted

Then why it doesn't get displayed anymore?

**Comment by valiafetisov** [comment]
> once the page is refreshed

What do you mean by `refreshed`? When it `is lost` is it lost from the store (probably `reset`?) or only from the component?

File: frontend/components/dashboard/CollateralTable.vue [hunk 1]
```diff
@@ -60,23 +74,6 @@
                 %
             </span>
         </div>
-        <div slot="icon" slot-scope="record" class="Element">
-            <CurrencyIcon :currency-symbol="record.symbol" />
-        </div>
```
Comment (valiafetisov) [inline frontend/components/dashboard/CollateralTable.vue:65]: Why did you need to remove `CurrencyIcon` and move `token address` column around to fix the problem? Is it unrelated improvement or a leftover?

File: frontend/containers/DashboardContainer.vue [hunk 2]
```diff
@@ -21,6 +21,12 @@ export default Vue.extend({
     components: {
         DashboardAuctionsView,
     },
+    props: {
+        network: {
+            type: String,
+            default: undefined,
+        },
+    },
```
Comment (valiafetisov) [inline frontend/containers/DashboardContainer.vue:29]: You actually don't need to pass it as a prop, since it's already a container and can use `...mapGetters(network, { network: 'getMakerNetwork' })` directly

File: frontend/components/dashboard/CollateralTable.vue (hunk 1 above)
Comment (valiafetisov) [reply frontend/components/dashboard/CollateralTable.vue:65]: Alright! Did it also change the order of columns in the UI or had no effect on it?

**Review by valiafetisov — APPROVED** [review]

**Review by LukSteib — APPROVED** [review]
