### PR TITLE
Wallet related fixes

### LINKED ISSUE #367: Fix known wallet related problems
### Goal
Improve overall wallet connection experience by fixing known issues

### Context
Recently we've encountered the following three problems that need to be addressed with this issue:
~1) Switching between accounts from within metamask modal is not reflected by the indicated wallet address in the header of our UI~
2) Disconnect connected wallet via button in header doesn't work
3) The auth states for the connected wallet are not properly fetched (While auth to withdraw DAI from VAT via wallet popup was given and correctly indicated when on `/collateral` page, the same step is indicated as requiring authorisation when on `/surplus` page.)

### Tasks
- [x] Fix problem 1)
- [x] Fix problem 2)
- [ ] Fix problem 3)

### Assets:
2)
https://www.loom.com/share/32fa7d678fa246ec9edebeda67dfa399

3)
unauth:
image

auth (same wallet)
image

### PR DESCRIPTION
**Pull request by zoey-kaiser**
Closes #367

Checklist:
- [X] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [X] issue checkboxes are all addressed
- [X] manually checked my feature / not applicable
- [X] wrote tests / not applicable
- [X] attached screenshots / not applicable

### CODE REVIEW

**Review by LukSteib — APPROVED** [review]

File: frontend/store/wallet.ts [hunk 1]
```diff
@@ -295,9 +298,12 @@ export const actions = {
...
         commit('reset');
         if (!getters.isConnected) {
-            await dispatch('autoConnect');
+            if (!WAS_WALLET_DISCONNECTED) {
+                await dispatch('autoConnect');
+            }
         }
         dispatch('refetch');
         dispatch('surplus/setup', undefined, { root: true });
+        WAS_WALLET_DISCONNECTED = false;
```
Comment (valiafetisov) [inline frontend/store/wallet.ts:307]: Using a local variable is a very hacky approach, since calling `setup` twice will no longer work and will autoconnect the wallet again. It just doesn't fix the problem, but introduces more side effects.

Instead, I would remove `await dispatch('autoConnect')` from the setup action (since it's only need to be called on the page load and not with every `setup`) and move it to the place where we call `setup` at the page load. I guess right before this line: https://github.com/sidestream-tech/unified-auctions-ui/blob/19a386750245af34e194f8717cc0d9495aa9db8d/frontend/plugins/vuex-persist.client.js#L17

**Review by LukSteib — APPROVED** [review]

**Review by valiafetisov — APPROVED** [review]
